steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'frontity-server', '--trigger-http', '--runtime', 'nodejs8', '--entry-point', 'default', '--source', '$PWD/build']
  dir: 'build'